### PR TITLE
Update to work with Node 12.13.1 LTS

### PR DESCRIPTION
**Pull request by BitsAndFlows**
Please update the plugin to work with Node 12.13.1 LTS so it can be used with HOOBS 3.1.1 :-).

### CODE REVIEW

**Comment by lucavb** [comment]
The thing is that this repo does not really rely on noble but on the [node-mi-flora](https://www.npmjs.com/package/node-mi-flora) which hasn't been updated for years now and it relies on noble. So I guess a replacement for this repo is needed and I don't see any on npmjs.

So the alternative would be to fork that repo and see if it works with node 12. Do you have any information that noble now supports node versions > 9? If so, I can look into this.

**Comment by Bladestar2105** [comment]
Please take a look at this project: https://github.com/abandonware/noble

**Comment by lucavb** [comment]
Alright, I did take a look at that thing. I forked and rewrote `node-mi-flora` to typescript [here](https://github.com/lucavb/node-mi-flora). I released this project, and will create a pull request. In the mean time, I am using this new project for a rewrite of this project. This is currently taking some time because the code is old and not exactly the best. I am doing my best and maybe I can do it by the end of the week.

**Comment by lucavb** [comment]
You can see the progress in https://github.com/lucavb/homebridge-mi-flora/tree/ts

**Comment by Bladestar2105** [comment]
Thank you very much!

**Comment by Sungamm** [comment]
Hey,

sorry but I am not sure can I use this plugin to add my Xiaomi Plant Sensors because I am running at Node LTS (12.xx). Not sure if I understood all details correct. 

Thank you for any help,

**Comment by lucavb** [comment]
I have kind of lost track of this repository because I worked on the esphome plugin, but I will try to finish the work over the easter holiday. I also dug out a battery for the plant sensor so that I can test it. Though I am just noticing that I don't have any Raspberry Pis anymore and my homebridge runs on a VM, but we'll see.

**Comment by Sungamm** [comment]
Thank you lucavb to invest time and effort in this!

**Comment by BitsAndFlows** [comment]
> I have kind of lost track of this repository because I worked on the esphome plugin, but I will try to finish the work over the easter holiday. I also dug out a battery for the plant sensor so that I can test it. Though I am just noticing that I don't have any Raspberry Pis anymore and my homebridge runs on a VM, but we'll see.

Maybe you should check out before https://github.com/Martvvliet/homebridge-mi-flora-filtered. After last Update it works for me with HOOBS (which has Node 12.13.1).

**Comment by Sungamm** [comment]
Hey! Thank you! Your are right! I installed the recommended plugin and indead it works with Node LTS. Thank you!

**Comment by lucavb** [comment]
Okay so I guess that is a solution. Maybe I'll finish writing the typescript stuff and after all I did the node-mi-flora updated as well. We'll see. Closing this for the moment then.

**Pull request closed without merging**
